#!/bin/bash
source $(dirname $0)/config

if pgrep pithos &> /dev/null; then
	echo -n "%{A:pithosc p:}%{F$COLOR_ICON}%{F-}%{A} "
	echo -n "$(pithosc c title)"
	echo -n "%{F$COLOR_ICON}"
	echo -n " %{A:pithosc love:}%{A}"
	echo -n " %{A:pithosc ban:}%{A}"
	echo -n "%{F-}"
fi
