#!/bin/sh

bspc config border_width        1
bspc config window_gap          2

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 16

bspc monitor LVDS1 -d W I T 1 2 3 4 5 6 7 8 9 0 \#
bspc monitor VGA1 -d C

# bspc monitor LVDS1 -d W \#W I \#I T \#T 1 \#1 2 \#2 3 \#3 4 \#4 5 \#5 6 \#6 7 \#7 8 \#8 9 \#9 0 \#0
# bspc monitor VGA1 -d C \#C

xsetroot -cursor_name left_ptr

SXHKD_SHELL=bash sxhkd -c ~/.files/bspwm/sxhkdrc &
#~/.config/bspwm/panel/panel &
~/.files/bin/-xrandr-autoconfig &
