#!/bin/zsh

typeset -ga cards
typeset -gA paths prevStatuss prevEDIDs
cards+=( VGA1 )
paths[VGA1]=/sys/class/drm/card0-VGA-1/

updateCard() {
	local card=$1
	local cardPath=$paths[$card]
	local cardStatus="$(cat $cardPath/status)"
	local prevStatus="$prevStatuss[$card]"
	local edid="$(cat $cardPath/edid)"
	local prevEDID="$prevEDIDs[$card]"
	echo $card $cardStatus
	local changed=$([[ "$cardStatus" != "$prevStatus" || "$edid" != "$prevEDID" ]] && echo "YES")

	if [[ "${cardStatus}" = disconnected ]]; then
		xrandr --output $card --off
	elif [[ "${cardStatus}" = connected ]]; then
		if grep "ViewSonic" $cardPath/edid; then
			xrandr --output $card --auto --left-of LVDS1
		else
			xrandr --auto
			cat $cardPath/edid
		fi
	fi
	if [[ "$changed" ]]; then
		echo $DISPLAY
		pkill -f -KILL i3/panel
		nohup sh -c ~/.files/i3/panel/panel &
		disown
	fi

	prevStatuss[$card]="$cardStatus"
	prevEDIDs[$card]="$edid"
}

update() {
	updateCard VGA1
	xrandr --output LVDS1 --mode 1366x768
}

update

# while inotifywait -e modify,create,delete,open,close,close_write,access $VGA1/cardStatus; do
while true; do
	update
	sleep 5
done
