#! /bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -c panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

echo "change:" > "$PANEL_FIFO" &
../i3-subscribe > "$PANEL_FIFO" &
while true; do echo "update"; sleep 1; done > "$PANEL_FIFO" &
# conky -c ./panel_conky > "$PANEL_FIFO" &
#dbus-monitor "type='signal', path='/net/kevinhmehall/Pithos'" > "$PANEL_FIFO" &

cat "$PANEL_FIFO" |\
	$(dirname $0)/panel_bar |\
	 bar \
	 	-f "$FONT1","$FONT2"\
	 	-F "$COLOR_FOREGROUND"\
	 	-B "$COLOR_BACKGROUND"\
	 	-g "$PANEL_GEOMETRY"\
	 	-u $LINEHEIGHT |\
	 sh -s &
wait
