#!/bin/bash
source $(dirname $0)/config
echo -n "%{F$COLOR_ICON}%{F-} $(date +'%H:%M %b %d %a') "

# case $(date +%b) in
# esac
#
# echo -n $(date +%d)
#
# case $(date +%a) in
# 	Sun) echo -n s;;
# 	Mon) echo -n M;;
# 	Tue) echo -n t;;
# 	Wed) echo -n W;;
# 	Thu) echo -n T;;
# 	Fri) echo -n F;;
# 	Sat) echo -n S;;
# esac
