#!/bin/bash
dir="/w/my/data/media"

session_id="$(tmux new-session -s ent -d -c "$dir/video" -P -F '#{session_id}')"

songs_video_pane_id="$(tmux new-window -t "$session_id" -d -n songs -c "$dir/video" -P -F '#{pane_id}')"
tmux split-window -t "$songs_video_pane_id" -d -h -c "$dir/songs"

songs_pane_id="$(tmux new-window -t "$session_id" -d -c /w/my/data/media/songs -n songs -P -F '#{pane_id}')"

tmux send-keys \
	-t "$(tmux new-window -t "$session_id:99" -d -c "$dir/video" -P -F '#{pane_id}')" \
	'print -s google-chrome-stable --user-data-dir=/w/my/data/tmp/chrome-rem --ozone-platform=wayland # --proxy-server=socks5://localhost:4711' Enter

exec tmux attach-session -t "$session_id"
