#!/bin/bash
session_id="$(tmux new-session -s temp -d -c /w/my/data/notes -P -F '#{session_id}')"
tmux send-keys -t "$session_id" 'e scratch' Enter

tmux send-keys \
	-t "$(tmux new-window -t "$session_id" -d -c /w/my/data/notes -P -F '#{pane_id}')" \
	'print -s brightness 5; ' \
	'print -s brightness max; ' \
	'print -s "volume 5; volume m"; ' \
	'print -s "xrandr --output HDMI-2 --mode 1920x1200 --right-of eDP-1; xrandr --output eDP-1 --pos 0x120"; ' \
	'print -s "xrandr --output HDMI-2 --off"; ' \
	Enter \
	'sudo udevadm control --reload; sudo udevadm trigger; sleep 2; xmodmap ~/.xmodmaprc; sudo tlp setcharge 60 70' Enter

exec tmux attach-session -t "$session_id"
