#!/bin/bash
session_id="$(tmux new-session -s temp -d -c /w/my/data/notes -P -F '#{session_id}')"
tmux send-keys -t "$session_id" 'e scratch' Enter

tmux send-keys \
	-t "$(tmux new-window -t "$session_id" -d -c /w/my/data/notes -P -F '#{pane_id}')" \
	'print -s brightness 5; ' \
	'print -s brightness max; ' \
	'print -s "volume 5; volume m"; ' \
	'print -s "xrandr --output HDMI-2 --mode 1920x1200 --left-of eDP-1; xrandr --output eDP-1 --pos 1920x120"; ' \
	'print -s "xrandr --output HDMI-2 --off"; ' \
	Enter \
	'sudo udevadm control --reload; sudo udevadm trigger; sleep 2; xmodmap ~/.xmodmaprc; sudo tlp setcharge 60 70' Enter

bt_pane_id="$(tmux new-window -t "$session_id" -d -c /w/my/data/notes -n BT -P -F '#{pane_id}')"
tmux send-keys \
	-t "$(tmux split-window -t "$bt_pane_id" -v -b -c /w/my/data/notes -P -F '#{pane_id}')" \
	'bluetoothctl' Enter
tmux send-keys \
	-t "$bt_pane_id" \
	'print -s pactl list sinks' Enter

tmux new-window -t "$session_id" -d -c /w/my/data/media/books/downloaded -n books

exec tmux attach-session -t "$session_id"
